# Generated by Django 4.1.2 on 2022-10-29 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lyric",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="artiste", name="age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lyric",
            name="song_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musicapp.song"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artiste_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musicapp.artiste"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="date_released",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
